// Generated by https://quicktype.io

export interface IResControl {
    sum:     number;
    controls: Control[];
}

export interface Control {
    _id?:    string;
    fecha: string;
    status?: boolean;
    hora: number;
    rating:  number;
    category?:  number;
    __v?:    number;
}
