version: '2'


services:
  estudiante:
    build: ./microservices/canal-service
    depends_on:  
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/canal
  idioma:
    build: ./microservices/programa-service
    depends_on:  
      - mongo
    environment:
      - PORT=3000
      - MONGODB_CNN=mongodb://mongo:27017/programa

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - canal
      - programa

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    
